In [ ]:
import pandas as pd
import numpy as np
from keras.models import Sequential, Model
from keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [ ]:
df=pd.read_csv("/content/kc_house_data.csv")
df_original=df
df.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

In [ ]:
df.head()
df=df.drop(columns=['date'])

In [ ]:
max=MinMaxScaler(feature_range=(0,1))
df=max.fit_transform(df)
print(df)
df=pd.DataFrame(df)
print(df)

[[0.72010308 0.01926557 0.09090909 ... 0.21760797 0.16193426 0.00574235]
 [0.64785332 0.06072131 0.09090909 ... 0.16611296 0.22216486 0.00802712]
 [0.56879485 0.01377049 0.06060606 ... 0.23754153 0.3994149  0.00851302]
 ...
 [0.15378321 0.04289849 0.06060606 ... 0.18272425 0.10686629 0.00155764]
 [0.0293272  0.04262295 0.09090909 ... 0.37375415 0.17398038 0.00073057]
 [0.15378321 0.03278689 0.06060606 ... 0.18272425 0.10686629 0.00081098]]
             0         1         2        3         4         5    6    7   \
0      0.720103  0.019266  0.090909  0.12500  0.067170  0.003108  0.0  0.0   
1      0.647853  0.060721  0.090909  0.28125  0.172075  0.004072  0.4  0.0   
2      0.568795  0.013770  0.060606  0.12500  0.036226  0.005743  0.0  0.0   
3      0.251157  0.069377  0.121212  0.37500  0.126038  0.002714  0.0  0.0   
4      0.197333  0.057049  0.090909  0.25000  0.104906  0.004579  0.0  0.0   
...         ...       ...       ...      ...       ...       ...  ...  ...   
21608  0.0

In [ ]:
X = df.iloc[:, 2:8]

print(X)


              2        3         4         5    6    7
0      0.090909  0.12500  0.067170  0.003108  0.0  0.0
1      0.090909  0.28125  0.172075  0.004072  0.4  0.0
2      0.060606  0.12500  0.036226  0.005743  0.0  0.0
3      0.121212  0.37500  0.126038  0.002714  0.0  0.0
4      0.090909  0.25000  0.104906  0.004579  0.0  0.0
...         ...      ...       ...       ...  ...  ...
21608  0.090909  0.31250  0.093585  0.000370  0.8  0.0
21609  0.121212  0.31250  0.152453  0.003206  0.4  0.0
21610  0.060606  0.09375  0.055094  0.000503  0.4  0.0
21611  0.090909  0.31250  0.098868  0.001132  0.4  0.0
21612  0.060606  0.09375  0.055094  0.000337  0.4  0.0

[21613 rows x 6 columns]


In [ ]:
Y=df.iloc[:,1]
print(Y)

0        0.019266
1        0.060721
2        0.013770
3        0.069377
4        0.057049
           ...   
21608    0.037377
21609    0.042623
21610    0.042898
21611    0.042623
21612    0.032787
Name: 1, Length: 21613, dtype: float64


In [ ]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

In [ ]:
#Sequential model
model=Sequential()

In [ ]:
X.shape

(21613, 6)

In [ ]:
#add hidden layer
model.add(Dense(180,activation='relu'))
model.add(Dense(90,activation='relu'))
model.add(Dense(1,activation='linear'))

In [ ]:
model.compile(optimizer='adam',loss='mean_squared_error',metrics=['mae'])

In [ ]:
model.fit(X_train, Y_train, epochs=10)

TypeError: ignored

In [ ]:
loss, accuracy=model.evaluate(X_test,Y_test)
print(f"test accuracy: {accuracy*100: .2f}")

136/136 [==============================] - 0s 2ms/step - loss: 0.0011 - mae: 0.0207
test accuracy:  2.07


In [ ]:
predictions=model.predict([X_test])
predictions.shape

136/136 [==============================] - 0s 1ms/step


(4323, 1)

In [ ]:
predictions[0]

array([0.03030874], dtype=float32)

In [ ]:
y_pred_original=max.inverse_transform(predictions)

ValueError: ignored